### ISSUE TITLE
Client Search not returning properly

### ISSUE THREAD

**Issue by behemphi** [coderanger/pychef#10]
I am using the following pattern for identifying nodes and it works a charm:

```
result_set = chef.Search('node', q="name:test*")
for result in result_set:
    node = chef.Node(result["name"])
    print node
```

Executing this works as expected. I get an object for each result.

I then attempt to apply this to clients:

```
result_set = chef.Search('client', q="name:test*")
for result in result_set:
    client = chef.Client(result["name"])
    print client
```

no result is shown on the screen, however I can verify there are three clients that should be present.

I will also mention here that there is nothing in the documentation about the Client object, I sort of guessed it would be there then read the code.  

I am not handy enough with Python to find the bug, though I have tried.

Thanks
Boyd Hemphill

**Comment by AlexanderJvV** [comment]
Hi @coderanger. Sorry to bother I'm having the same issue as mentioned above. But when i then run the code I get "ChefServerNotFound: object not found" error. But it works when I'm trying to get all the nodes names. I need to create an api that gets all the information for one node.
