### ISSUE TITLE
knife cookbook list?

### ISSUE THREAD

**Issue by gliptak** [coderanger/pychef#57]
I might have missed this in the documentation, but is there an equivalent of ```knife cookbook list``` with ```pychef```? Thanks

**Comment by coderanger** [comment]
No, there are two different pull requests open to add this API but neither were mergable last time I looked.

**Comment by coderanger** [comment]
You can always use raw API access though:

```python
api['/cookbooks']
```

**Comment by gliptak** [comment]
I see, I didn't check the outstanding pull requests. What updates this one requires before it can be merged?

https://github.com/coderanger/pychef/pull/20

**Comment by gliptak** [comment]
I modified https://github.com/coderanger/pychef/pull/20 to just basic list and versions functionality (save throws a ```ChefServerError``` ...) Would you be interested in reviewing?

**Comment by coderanger** [comment]
Not at the moment, given the workarounds for `GET` access being so easy, I don't want to tackle that API right now.

**Comment by gliptak** [comment]
I'm now using ```api['/cookbook']``` in my own code. Thanks
