### ISSUE TITLE
knife job support?

### ISSUE THREAD

**Issue by gliptak** [coderanger/pychef#58]
Would support for ```knife job``` API be on the roadmap? Thanks

**Comment by coderanger** [comment]
I've never deployed Push Jobs, so probably not.

**Comment by gliptak** [comment]
Would you be interested in a PR? Thanks

**Comment by coderanger** [comment]
I would probably put that in its own library, just given how few people use Push Jobs. It's a super niche tool.

**Comment by gliptak** [comment]
Thank you for the suggestion.
