### ISSUE TITLE
How to uninstall pychef modules from OSX 10.11 EI Capitan

### ISSUE THREAD

**Issue by alexya** [coderanger/pychef#59]
I ran `sudo python setup.py install' under pychef 0.3.0 folder and installed it. 
all the files were installed to /Library/Python/2.7/site-packages/PyChef-0.3.0-py2.7.egg

but when I tried to use 
```
    from chef.api import autoconfigure
    from chef.node import Node

    api = autoconfigure()
```
I always got errors:
```
/usr/bin/python /Users/alexya/Source/chef/chef.py
Traceback (most recent call last):
  File "/Users/alexya/Source/chef/chef.py", line 3, in <module>
    from chef.api import autoconfigure
  File "/Users/alexya/Source/chef/chef.py", line 3, in <module>
    from chef.api import autoconfigure
ImportError: No module named api
```

I don't know how to fix it. even if I tried by the sample in readme.rst
```
    from chef import autoconfigure, Node
    
    api = autoconfigure()
    n = Node('web1')
    print n['fqdn']
    n['myapp']['version'] = '1.0'
    n.save()
```
I still got the similar errors. 

my colleague suggested me to install pychef by pip. so, I want to know, how can I uninstall pychef from my OSX system? and then I will try to create a virtualenv and use pip to install it.

thx a lot.

**Comment by coderanger** [comment]
There is no specific way to uninstall Python libraries not installed with pip. You'll have to remove all the files manually.
