### ISSUE TITLE
Allow setting of Node attributes at different precedence levels

### ISSUE THREAD

**Issue by maus-** [coderanger/pychef#60]
Right now if I'm groking pychef / docs correctly it looks like you can only set node attributes at the "normal" level. https://github.com/coderanger/pychef/blob/master/chef/node.py#L195

I'd like to be able to set them arbitrarily to any level of precedence. Is this do-able in the existing pychef?

**Comment by coderanger** [comment]
That's not a feature of Chef, so no. All other levels get wiped at the start of the converge.
